### ISSUE TITLE
what is the state of this plugin? 

### ISSUE THREAD

**Issue by kevohagan** [dangerdespain/ah-graphql-plugin#3]
I have stumbled upon this plugin (havent tried it yet), but i was just wondering what state is it in? I would like to investigate ah+graphql but have not much knowledge in any of the two.. Is it something feasible? Or should i move to express or equivalent? Thanks for your insights! :)

**Comment by dangerdespain** [comment]
Hi @kevohagan! I'm currently usIng a modified version of this plugin in production and am loving it. This plugin should work as-is if instructions are followed. If there's interest, maybe I could build up an AH/GraphQL boilerplate project. I prefer Actionhero over Express, as it feels more declarative and I understand the core well. The community support is also fantastic (check out the Slack channel!). Please reach out if you have any questions, I'd love to see more people using this stack!

**Comment by kevohagan** [comment]
Okay thanks! I'll give it a go and i'll check out the slack channel! :) Btw how does this compare to : https://github.com/apollographql/graphql-server ?
